[project]
name = "llll-py"
version = "0.1.0"
description = "A basic package for parsing lisp-like linked lists in Python."
authors = [
	{ name = 'Felipe Tovar-Henao', email = 'felipe.tovar.henao@gmail.com' },
]
readme = "README.md"
keywords = ['lisp-like linked lists', 'bach']
requires-python = ">=3.10"
dependencies = ["typing_extensions"]
license = { file = "LICENSE" }

[tool.hatch.build.targets.wheel]
packages = ["src/llll"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
